### ISSUE TITLE
UPDATE Outdated ContextBroker Scripts.

### ISSUE THREAD

**Issue by abbasahmad** [telefonicaid/fiware-figway#4]
Hello i have sent a mail but got no feedback.

I have updated the Fiware-Figway "ContextBroker" part only.

You can find the readme and the code here : https://bitbucket.org/eglobalmark/egm_testexecorioncb/src/d2bdcff1dcc42efbb3cb4e015d8f7bfc06136cb0/ContextBroker/?at=master

Please let me know if you have any question.

I want to share those scripts via the official Fiware figware Git thats why i am asking you for an update.

**Comment by abbasahmad** [comment]
No? Nobody ? @flopezag @cralli @fgalan @LeandroGuillen

**Comment by fgalan** [comment]
Not sure about this (the owner of this repo is @cralli , as far as I understand) but in general, contributions are always welcome to FIWARE open source components. The usual (not sure if call it "official" :) contribution mechanis is doing a pull request (PR) on the target repository.

**Comment by abbasahmad** [comment]
Done. Thanks!
